services:
  postgres:
    image: postgres:17.5
    container_name: payment-processing-ca-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB}::${POSTGRES_USER}::${POSTGRES_PASSWORD}|${POSTGRES_TEST_DB}::${POSTGRES_TEST_USER}::${POSTGRES_TEST_PASSWORD}
    volumes:
      - ${POSTGRES_DATA_DIR:-/opt/payment-processing-data/db}:/var/lib/postgresql/data
      - ${POSTGRES_BACKUPS_DIR:-/opt/payment-processing-data/backups}:/var/lib/postgresql/backups
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  pgbouncer:
    image: edoburu/pgbouncer:v1.24.1-p1
    container_name: payment-processing-ca-pgbouncer
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./src/payment_processing_service/config/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./src/payment_processing_service/config/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-h', 'localhost' ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:8.0.2-bookworm
    container_name: payment-processing-ca-redis
    ports:
      - "0.0.0.0:${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ${REDIS_DATA_DIR:-/opt/payment-processing-data/redis}:/data
    command: /bin/sh -c "redis-server --requirepass '${REDIS_PASSWORD}'"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: payment-processing-ca-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    ports:
      - "0.0.0.0:${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "0.0.0.0:${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    volumes:
      - ${RABBITMQ_DATA_DIR:-/opt/payment-processing-data/rabbitmq}:/var/lib/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    container_name: payment-processing-ca-jaeger
    ports:
      - "16686:16686"  # Порт для Jaeger UI
      - "14268:14268"  # Порт для приёма spans (можно оставить, если не используете хранилище)
      - "4317:4317"   # OpenTelemetry gRPC
      - "4318:4318"   # OpenTelemetry HTTP
      - "9411:9411"  # Порт для совместимости с Zipkin
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411  # Включение совместимости
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: payment-processing-ca-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT:-2181}
      ZOOKEEPER_SERVER_ID: ${ZOOKEEPER_SERVER_ID:-1}
    ports:
      - "0.0.0.0:${ZOOKEEPER_PORT:-2181}:${ZOOKEEPER_PORT:-2181}"
    volumes:
      - ${ZOOKEEPER_DATA_DIR:-/opt/payment-processing-data/zookeeper}:/var/lib/zookeeper/
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: payment-processing-ca-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT:-2181}"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:${KAFKA_PORT:-9092}"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:${KAFKA_PORT:-9092}"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "0.0.0.0:${KAFKA_PORT:-9092}:${KAFKA_PORT:-9092}"
    volumes:
      - ${KAFKA_DATA_DIR:-/opt/payment-processing-data/kafka}:/var/lib/kafka/
    depends_on:
      - zookeeper
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 120s

  wait-for-services:
    image: atkrad/wait4x
    container_name: payment-processing-ca-wait-for-services
    command: tcp redis:${REDIS_PORT} pgbouncer:${POSTGRES_PORT} rabbitmq:${RABBITMQ_MANAGEMENT_PORT} kafka:${KAFKA_PORT} --timeout 180s --interval 10s --backoff-policy exponential --backoff-exponential-coefficient 2.0 --backoff-exponential-max-interval 300s
    restart: "no"
    depends_on:
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_healthy

  app-backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: payment-processing-backend-ca-test:latest
    container_name: payment-processing-ca-app-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - ./.env.test
    volumes:
      - .:/app
      - ./.env.test:/app/.env
    command: /bin/sh -c "uvicorn --host 0.0.0.0 --port ${BACKEND_PORT} --loop uvloop ${BACKEND_CONTAINER_COMMAND} src.payment_processing_service.main:app"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${BACKEND_PORT}/api/v1/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      wait-for-services:
        condition: service_completed_successfully

  app-consumer-rabbit:
    image: payment-processing-backend-ca-test:latest
    container_name: payment-processing-ca-app-consumer-rabbit
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env.test
    volumes:
      - ./:/app
      - ./.env.test:/app/.env
    command: /bin/sh -c "python src/payment_processing_service/presentation/consumers/rabbit.py"
    restart: always
    depends_on:
      wait-for-services:
        condition: service_completed_successfully

  app-consumer-kafka:
    image: payment-processing-backend-ca-test:latest
    container_name: payment-processing-ca-app-consumer-kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env.test
    volumes:
      - ./:/app
      - ./.env.test:/app/.env
    command: /bin/sh -c "python src/payment_processing_service/presentation/consumers/kafka.py"
    restart: always
    depends_on:
      wait-for-services:
        condition: service_completed_successfully

  test-runner:
    image: payment-processing-backend-ca-test:latest
    container_name: payment-processing-ca-test-runner
    env_file:
      - ./.env.test
    volumes:
      - ./:/app
      - ./.env.test:/app/.env
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/default-reports
    depends_on:
      - postgres
      - rabbitmq
      - kafka
    command: /bin/sh -c "tail -f /dev/null"
    restart: unless-stopped

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
